sudo: false
 
language: node_js
 
before_install:
  - curl https://install.meteor.com | /bin/sh
  - npm install -g mupx
  - export PATH="$HOME/.meteor:$PATH"
 
cache:
  directories:
    - node_modules
    - .meteor
 
before_script:
  - meteor npm install
 
script:
  - meteor npm run test
  
after_success:
  - echo "-----BEGIN RSA PRIVATE KEY-----" > app-deployment-key 
  - env | grep -oP 'APPDEPLOYMENTKEY\=\K.*' | fold -w 64 >> app-deployment-key
  - echo "-----END RSA PRIVATE KEY-----" >> app-deployment-key
  - test $TRAVIS_BRANCH == "development" && mupx deploy
  - test $TRAVIS_BRANCH == "development" && chmod 600 app-deployment-key && ssh -o StrictHostKeyChecking=no -i app-deployment-key data-furnace@46.101.183.252 'export LC_ALL=C.UTF-8 && cd data-furnace && git pull origin development && mongo --port 27017 data-furnace --eval "printjson(db.dropDatabase())" && mongorestore --port 27017 --db data-furnace .mongodb-dump/meteor/'
