sudo: false
 
language: node_js
 
before_install:
  - curl https://install.meteor.com | /bin/sh
  - export PATH="$HOME/.meteor:$PATH"
 
cache:
  directories:
    - node_modules
 
before_script:
  - meteor npm install
 
script:
  - meteor npm run test
